version: '3.8'

services:
  ledger:
    image: docker.io/your-org/ledger:latest
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - backend

  transfer:
    image: docker.io/your-org/transfer:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - ledger
    networks:
      - backend

networks:
  backend:
    driver: bridge
